- name: Deploy to Azure VM
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF' | tee ~/deploy.log
      cd ~/retailtech
      git pull origin main

      # Backend
      cd retailtechbackend
      npm install
      pm2 restart app || pm2 start app.js --name app

      # Frontend
      cd ../retailtechfrontend
      npm install
      npm run build
      sudo rm -rf /var/www/html/*
      sudo cp -r dist/* /var/www/html/
    EOF

