name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            LOG_FILE=~/deploy.log
            echo "Deployment started at $(date)" > $LOG_FILE

            # Backend
            echo "Deploying backend..." >> $LOG_FILE
            cd ~/retailtechbackend
            git pull origin main >> $LOG_FILE 2>&1
            npm install >> $LOG_FILE 2>&1
            pm2 restart app || pm2 start app.js --name app >> $LOG_FILE 2>&1

            # Frontend
            echo "Deploying frontend..." >> $LOG_FILE
            cd ~/retailtechfrontend
            git pull origin main >> $LOG_FILE 2>&1
            npm install >> $LOG_FILE 2>&1
            npm run build >> $LOG_FILE 2>&1
            sudo rm -rf /var/www/html/* >> $LOG_FILE 2>&1
            sudo cp -r dist/* /var/www/html/ >> $LOG_FILE 2>&1

            echo "Deployment finished at $(date)" >> $LOG_FILE
          EOF

